package jarl

DEBUG_MODE :: true

TIMING_HISTORY_SIZE :: 30

IMGUI_ENABLED :: true

GL_MAJOR_VERSION :: 4
GL_MINOR_VERSION :: 5
GLSL_VERSION :: "#version 450"

SHADER_DEFAULT_RAY_MAX_STEPS :: 1500
SHADER_DEFAULT_RAY_MAX_DIST :: 200.0
SHADER_DEFAULT_RAY_MAX_TELEPORTS :: 8